spring.application.name=email-service-projekt2
#spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
#spring.rabbitmq.port=5671
#spring.rabbitmq.username=tkvucuuc
#spring.rabbitmq.password=9Yh7AkX4xLI2EVUryrMrZHHinnQk-Zye
#spring.rabbitmq.virtual-host=tkvucuuc
#spring.rabbitmq.ssl.enabled=true
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
